routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('project', 'ProjectController');

Route::resource('requirement', 'RequirementController')->except([
    'index', 'create'
]);
Route::resource('task', 'TaskController');

Route::resource('people', 'PeopleController');

Route::resource('meeting', 'MeetingController');

app/Meeting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Meeting extends Model
{
  protected $fillable = [
      'project_name', 'people_names', 'meeting_date', 'meeting_time', 'meeting_duration', 'meeting_description'
  ];
}

app/Http/Controllers/MeetingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Meeting;
use App\People;
use App\Project;

class MeetingController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $meetings = Meeting::all();
        $projects = Project::all();
        $peoples = People::all();
        return view('meeting.index',['meetings' => $meetings, 'projects' => $projects, 'peoples' => $peoples]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('meeting.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
          'project_name' => 'required',
          'people_names' => 'required',
          'meeting_date' => 'required',
          'meeting_time' => 'required',
          'meeting_duration' => 'required',
          'meeting_description' => 'required',
      ]);

        $meeting = new Meeting();

        $peoplenames = $request->input('people_names');
        $peoplenames = implode(',', $peoplenames);

        // $input = $request->except('people_names');
        // //Assign the "mutated" news value to $input
        // $input['people_names'] = $peoplenames;

        $meeting->project_name        = $request->project_name;
        $meeting->people_names    = $peoplenames;
        $meeting->meeting_date       = $request->meeting_date;
        $meeting->meeting_time      = $request->meeting_time;
        $meeting->meeting_duration      = $request->meeting_duration;
        $meeting->meeting_description = $request->meeting_description;

        $meeting->save();

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $meeting = Meeting::findOrFail($id);
        return view('meeting.show',['meeting' => $meeting]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $meeting = Meeting::findOrFail($id);
        // $projects = Project::all();
        // $peoples = People::all();
        return view('meeting.edit',['meeting'=> $meeting]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $meeting = Meeting::findOrFail($id);

        $peoplenames = $request->input('people_names');
        $peoplenames = implode(',', $peoplenames);

        // $input = $request->except('people_names');
        // //Assign the "mutated" news value to $input
        // $input['people_names'] = $peoplenames;

        $meeting->project_name        = $request->project_name;
        $meeting->people_names    = $peoplenames;
        $meeting->meeting_date       = $request->meeting_date;
        $meeting->meeting_time      = $request->meeting_time;
        $meeting->meeting_duration      = $request->meeting_duration;
        $meeting->meeting_description = $request->meeting_description;

        $meeting->save();

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $meeting = Meeting::findOrFail($id);
      $meeting->delete();
      return back();
    }
}

resources/views/meeting/create.blade.php
<form id="meeting" action="{{ route('meeting.store')}}" method="POST">
    @csrf
    <div class="form-group">
        <div class="form-row">
            <div class="col-lg-6">
                <label for="selectProject"> Project Name: </label>
                <select class="form-control{{ $errors->has('project_name') ? ' is-invalid' : '' }}" name="project_name" id="selectProject">
                    <option selected> Choose Project........... </option>
                    @foreach ($projects as $project)
                    <option value="{{ $project->project_name}}"> {{ $project->project_name}} </option>
                    @endforeach
                </select>
                @if ($errors->has('project_name'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('project_name') }}</strong>
                    </span>
                @endif
            </div>
            <div class="col-lg-6">
                <label for="selectProject"> Add People: </label>
                <select class="form-control" multiple name="people_names[]" id="selectProject" required>
                    @foreach ($peoples as $people)
                    <option value="{{ $people->name}}"> {{ $people->name}} </option>
                    @endforeach
                </select>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="form-row">
            <div class="col-lg-5">
                <label for="meetingDate"> Meeting Date: </label>
                <input type="date" name="meeting_date" id="meetingDate" class="form-control{{ $errors->has('meeting_date') ? ' is-invalid' : '' }}">
                @if ($errors->has('meeting_date'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('meeting_date') }}</strong>
                    </span>
                @endif
            </div>
            <div class="col-lg-4">
                <label for="meetingTime"> Meeting Time: </label>
                <input type="time" name="meeting_time" id="meetingTime" class="form-control{{ $errors->has('meeting_time') ? ' is-invalid' : '' }}">
                @if ($errors->has('meeting_time'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('meeting_time') }}</strong>
                    </span>
                @endif
            </div>
            <div class="col-lg-3">
                <label for="meetingDuration"> Duration: </label>
                <input type="text" name="meeting_duration" id="meetingDuration" class="form-control{{ $errors->has('meeting_duration') ? ' is-invalid' : '' }}">
                @if ($errors->has('meeting_duration'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('meeting_duration') }}</strong>
                    </span>
                @endif
            </div>
        </div>
    </div>

    <div class="form-group">
        <label for="projectDescription"> Description: </label>
        <textarea class="form-control{{ $errors->has('meeting_description') ? ' is-invalid' : '' }}" name="meeting_description" id="projectDescription" cols="30" rows="3"></textarea>
        @if ($errors->has('meeting_description'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('meeting_description') }}</strong>
            </span>
        @endif
    </div>
</form>

resources/views/meeting/edit.blade.php
<form id="editMeeting" action="{{ route('meeting.update', $meeting->id)}}" method="POST">
    @csrf @method('put')
    <div class="form-group">
        <div class="form-row">
            <div class="col-lg-6">
                <label for="selectProject"> Project Name: </label>
                <select class="form-control" name="project_name" id="selectProject">
                    <option selected> Choose Project........... </option>
                    @foreach ($projects as $project)
                      <option value="{{ $project->project_name}}" @if ($project->project_name == $meeting->project_name)  selected class="text-primary" @endif> {{ $project->project_name}} </option>
                    @endforeach
                </select>
            </div>
            <div class="col-lg-6">
                <label for="selectProject"> Add People: </label>
                <select class="form-control" multiple name="people_names[]" id="selectProject">
                    @foreach ($peoples as $people)
                    <option value="{{ $people->name}}"> {{ $people->name}} </option>
                    @endforeach
                </select>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="form-row">
            <div class="col-lg-5">
                <label for="meetingDate"> Date: </label>
                <input type="date" name="meeting_date" value="{{ $meeting->meeting_date }}" id="meetingDate" class="form-control" required>
            </div>
            <div class="col-lg-4">
                <label for="meetingTime"> Time: </label>
                <input type="time" name="meeting_time" value="{{ $meeting->meeting_time }}" id="meetingTime" class="form-control" required>
            </div>
            <div class="col-lg-3">
                <label for="meetingDuration"> Duration: </label>
                <input type="text" name="meeting_duration" value="{{ $meeting->meeting_duration}}" id="meetingDuration" class="form-control" required>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label for="projectDescription"> Description: </label>
        <textarea class="form-control" name="meeting_description" id="projectDescription" cols="30" rows="3" required>{{ $meeting->meeting_description}}</textarea>
    </div>
</form>




{{-- <form id="editMeeting" action="{{ route('people.update',$meeting->id) }}" method="post">
    @csrf @method('put')
    <div class="form-group">
        <div class="form-row">
            <div class="col-lg-6">
                <label for="selectProject"> Project Name: </label>
                <select class="form-control" name="project_name" id="selectProject">
                    @foreach ($projects as $project)
                      <option value="{{ $project->project_name}}" @if ($project->project_name == $meeting->project_name)  selected class="text-primary" @endif> {{ $project->project_name}} </option>
                    @endforeach
                </select>
            </div>
            <div class="col-lg-6">
                <label for="selectProject"> Add People: {{$meeting->people_names}} </label>
                <select class="form-control" multiple name="people_names[]" id="selectProject">
                    @foreach ($peoples as $people)
                     <option value="{{ $people->name }}"> {{ $people->name}} </option>
                    @endforeach
                </select>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="form-row">
            <div class="col-lg-5">
                <label for="meetingDate"> Date: </label>
                <input type="date" name="meeting_date" value="{{ $meeting->meeting_date}}" id="meetingDate" class="form-control" required>
            </div>
            <div class="col-lg-4">
                <label for="meetingTime">  Time: </label>
                <input type="time" name="meeting_time" value="{{ $meeting->meeting_time}}" id="meetingTime" class="form-control" required>
            </div>
            <div class="col-lg-3">
                <label for="meetingDuration">  Duration: </label>
                <input type="text" name="meeting_duration" value="{{ $meeting->meeting_duration}}" id="meetingDuration" class="form-control" required>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label for="projectDescription"> Description: </label>
        <textarea class="form-control" name="meeting_description" id="projectDescription" cols="30" rows="3" required>{{ $meeting->meeting_description}}</textarea>
    </div>
</form> --}}

resources/views/meeting/index.blade.php
@extends('layouts.app')

@section('title', 'People')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-3">
          @include('includes.sidebar')
        </div>
        <div class="col-md-9">
          <div class="card">
              <div class="card-header">
                <div class="row">
                  <div class="col-lg-6">
                      <h5> All Meeting </h5>
                  </div>
                  <div class="col-lg-6">
                    <div class="text-right">
                      <button type="button" class="btn btn-outline-success btn-sm" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#createMeetingModal">
                          <i class="fas fa-mail-bulk"></i> Create Meeting
                      </button>
                    </div>
                    <!-- add Requirement modal code start -->
                    <div class="modal fade" id="createMeetingModal" tabindex="-1" role="dialog">
                      @if(count($errors) > 0)
                          <script type="text/javascript">
                            $('#createMeetingModal').modal('show');
                          </script>
                      @endif
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title"> Create Meeting </h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true"> &times; </span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                  @include('meeting.create',['peoples' => $peoples, 'projects' => $projects])
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-outline-danger btn-sm" data-dismiss="modal"> <i class="fas fa-times"></i> Close </button>
                                    <button form="meeting" type="submit" class="btn btn-outline-success btn-sm"> <i class="fas fa-plus"></i> Save </button>
                                </div>
                            </div>
                        </div>
                    </div> <!-- add Requirement modal code end -->
                  </div>
                </div>
              </div>
              <div class="card-body">
                <table class="table table-bordered table-hover table-sm">
                    <thead>
                        <th class="text-center"> Project Name </th>
                        <th class="text-center"> Date </th>
                        <th class="text-center"> Time </th>
                        <th class="text-center"> Duration </th>
                        <th class="text-center"> View </th>
                        <th class="text-center"> Edit </th>
                        <th class="text-center"> Delete </th>
                    </thead>
                    <tbody>
                        @foreach ($meetings as $meeting)
                        <tr>
                            <td class="text-center"> {{ $meeting->project_name }} </td>
                            <td class="text-center"> {{ $meeting->meeting_date }} </td>
                            <td class="text-center"> {{ $meeting->meeting_time }} </td>
                            <td class="text-center"> {{ $meeting->meeting_duration }} </td>
                            <td>
                                <div class="text-center">
                                  <a href="{{route('meeting.show', $meeting->id)}}" class="btn btn-outline-success btn-sm" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#viewMeetingModal{{$meeting->id}}">
                                      <i class="fas fa-eye"></i>
                                  </a>
                                </div>
                                <!-- This below code edit madal Requirement -->
                                <div class="modal fade" id="viewMeetingModal{{$meeting->id}}" tabindex="-1" role="dialog">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title"> Meeting Details </h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                  <span aria-hidden="true"> &times; </span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                              @include('meeting.show')
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-outline-danger btn-sm" data-dismiss="modal"> <i class="fas fa-times"></i> Close </button>
                                            </div>
                                        </div>
                                    </div>
                                </div> <!-- End of the edit Requirement modal code -->
                            </td>
                            <td>
                                <div class="text-center">
                                  <a href="{{route('meeting.edit', $meeting->id)}}" class="btn btn-outline-info btn-sm" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#editMeetingModal{{$meeting->id}}">
                                      <i class="fas fa-edit"></i>
                                  </a>
                                </div>
                                <!-- This below code edit madal meeting -->
                                <div class="modal fade" id="editMeetingModal{{$meeting->id}}" tabindex="-1" role="dialog">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title"> Edit Meeting </h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                  <span aria-hidden="true"> &times; </span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                              @include('meeting.edit')
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-outline-danger btn-sm" data-dismiss="modal"> <i class="fas fa-times"></i> Close </button>
                                                <button form="editMeeting" type="submit" class="btn btn-outline-success btn-sm"> <i class="far fa-edit"></i> Save </button>
                                            </div>
                                        </div>
                                    </div>
                                </div> <!-- End of the edit meeting modal code -->
                            </td>
                            <td class="text-center">
                              <form action="{{ route('meeting.destroy',$meeting->id)}}" method="post">
                                @csrf @method('delete')
                                <button type="submit" class="btn btn-outline-danger btn-sm"> <i class="far fa-trash-alt"></i> </button>
                              </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
              </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/meeting/show.blade.php
  <h4 class="text-center"> {{ $meeting->project_name }} </h4>
  <p class="text-center">
    <span> <b> Date: </b> {{ $meeting->meeting_date }} </span>
    <span> <b> Time: </b> {{ $meeting->meeting_time }} </span>
    <span> <b> Duration: </b> {{ $meeting->meeting_duration }} </span>
  </p>

  <hr>
 <b> Called People: </b>
    @php
    $pizza = $meeting->people_names;
    $pieces = explode(',', $pizza);
    $size = sizeof($pieces)
    @endphp

    @for ($i = 0; $i < $size; $i++)
      <div>
        <p> {{ $i + 1 }}. {{ $pieces[$i] }} </p>
      </div>
    @endfor
  <p class="text-justify"> <b> Description: </b> {{ $meeting->meeting_description}} </p>