routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('project', 'ProjectController');

Route::resource('requirement', 'RequirementController')->except([
    'index', 'create'
]);
Route::resource('task', 'TaskController');

Route::resource('people', 'PeopleController');

Route::resource('meeting', 'MeetingController');

app/Requirement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Requirement extends Model
{
  protected $fillable = [
      'project_id','req_name', 'req_deadline', 'customer_priority', 'req_estimate', 'req_description'
  ];
  public function project()
    {
        return $this->belongsTo('App\Project');
    }
}

app/Http/Controllers/RequirementController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Requirement;
use App\Project;

class RequirementController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
          'req_name' => 'required',
          'req_priority' => 'required',
          'req_estimate' => 'required',
          'req_deadline' => 'required',
          'req_description' => 'required',
      ]);

        $requirement = new Requirement();
        //$project = Project::findOrFail($id);

        $requirement->project_id = $request->project_id;
        $requirement->req_name        = $request->req_name;
        $requirement->req_priority    = $request->req_priority;
        $requirement->req_estimate       = $request->req_estimate;
        $requirement->req_deadline      = $request->req_deadline;
        $requirement->req_description      = $request->req_description;

        $requirement->save();

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $requirement = Requirement::findOrFail($id);
      return view('requirement.show',['requirement' => $requirement]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $requirement = Requirement::findOrFail($id);
        return view('requirement.edit',['requirement' => $requirement]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
          'req_name' => 'required',
          'req_priority' => 'required',
          'req_estimate' => 'required',
          'req_deadline' => 'required',
          'req_description' => 'required',
      ]);

        $requirement = Requirement::findOrFail($id);
        //$project = Project::findOrFail($id);

        $requirement->project_id = $request->project_id;
        $requirement->req_name        = $request->req_name;
        $requirement->req_priority    = $request->req_priority;
        $requirement->req_estimate       = $request->req_estimate;
        $requirement->req_deadline      = $request->req_deadline;
        $requirement->req_description      = $request->req_description;

        $requirement->save();

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $requirement = Requirement::findOrFail($id);
      $requirement->delete();
      return back();
    }
}

resources/views/requirement/create.blade.php
<form id="requirement" action="{{ route('requirement.store') }}" method="post">
    @csrf
    <input type="hidden" name="project_id" value="{{ $project_id }}" />
    <div class="form-group">
        <label for="requirementname"> Name: </label>
        <input type="text" name="req_name" id="requirementname" class="form-control" required>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-lg-6">
                <label for="priority"> Priority: </label>
                <select name="req_priority" class="form-control" id="priority" required>
                    <option value="High"> High </option>
                    <option value="Middle"> Middle </option>
                    <option value="Low"> Low </option>
                </select>
            </div>
            <div class="col-lg-6">
                <label for="estimate"> Estimate: </label>
                <input type="text" name="req_estimate" id="estimate" class="form-control" required>
            </div>
        </div>
    </div>
    <div class="for-group">
        <label for="deadline"> Deadline: </label>
        <input type="date" name="req_deadline" id="deadline" class="form-control" required>
    </div>
    <div class="for-group">
        <label for="reqDes"> Description: </label>
        <textarea name="req_description" id="reqDes" cols="30" rows="3" class="form-control"></textarea>
    </div>
</form>

resources/views/requirement/edit.blade.php
<form id="editRequirement" action="{{ route('requirement.update',$requirement->id) }}" method="post">
    @csrf @method('put')
    <input type="hidden" name="project_id" value="{{ $requirement->project_id }}" />
    <div class="form-group">
        <label for="reqname"> Requirement Name: </label>
        <input type="text" name="req_name" value="{{ $requirement->req_name }}" id="reqname" class="form-control">
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-lg-6">
                <label for="priority"> Priority: {{ $requirement->req_priority }} </label>
                <select name="req_priority"  class="form-control" id="priority">
                    <option value="High"> High </option>
                    <option value="Middle"> Middle </option>
                    <option value="Low"> Low </option>
                </select>
            </div>
            <div class="col-lg-6">
                <label for="estimate"> Estimate: </label>
                <input type="text" name="req_estimate" value="{{ $requirement->req_estimate }}" id="estimate" class="form-control">
            </div>
        </div>
    </div>
    <div class="for-group">
        <label for="deadline"> Deadline: </label>
        <input type="date" name="req_deadline" value="{{ $requirement->req_deadline }}" id="deadline" class="form-control">
    </div>
    <div class="for-group">
        <label for="reqDes"> Description: </label>
        <textarea name="req_description" id="reqDes" cols="30" rows="3" class="form-control">{{ $requirement->req_description }}</textarea>
    </div>
</form>

resources/views/requirement/show.blade.php
<h4 class="text-center text-success"> {{ $requirement->req_name }} </h4>

<div class="row">
  <div class="col-lg-4">
    <p> <b> Priority: </b> {{ $requirement->req_priority }} </p>
  </div>
  <div class="col-lg-3">
    <p> <b> Estimate: </b> {{ $requirement->req_estimate }} </p>
  </div>
  <div class="col-lg-5">
    <p> <b> Deadline: </b> {{ $requirement->req_deadline }} </p>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <p class="text-justify"> <b> Description: </b> {{ $requirement->req_description}} </p>
  </div>
</div>