routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('project', 'ProjectController');

Route::resource('requirement', 'RequirementController')->except([
    'index', 'create'
]);
Route::resource('task', 'TaskController');

Route::resource('people', 'PeopleController');

Route::resource('meeting', 'MeetingController');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
  protected $fillable = [
      'project_id','people_names', 'task_name', 'task_progress', 'task_priority', 'task_deadline'
  ];

    public function project()
    {
        return $this->belongsTo('App\Project');
    }

    public function peoples()
    {
      return $this->hasMany('App\People');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Task;
use App\Project;

class TaskController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $tasks = Task::all();
        return view('task.advancement',['tasks' => $tasks]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
          'task_name' => 'required',
          'project_id' => 'required',
          'task_priority' => 'required',
          'task_progress' => 'required',
          'task_deadline' => 'required',
          'people_names' => 'required',
      ]);

        $task = new Task();

        $task->task_name        = $request->task_name;
        $task->project_id       = $request->project_id;
        $task->task_priority      = $request->task_priority;
        $task->task_progress      = $request->task_progress;
        $task->task_deadline = $request->task_deadline;
        $task->people_names    = $request->people_names;

        $task->save();

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $task = Task::findOrFail($id);
      return view('task.edit',['task' => $task]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
        'task_name' => 'required',
        'project_id' => 'required',
        'task_priority' => 'required',
        'task_progress' => 'required',
        'task_deadline' => 'required',
        'people_names' => 'required',
      ]);

        $task = Task::findOrFail($id);
        //$project = Project::findOrFail($id);

        $task->project_id     = $request->project_id;
        $task->task_name      = $request->task_name;
        $task->task_priority  = $request->task_priority;
        $task->task_progress  = $request->task_progress;
        $task->task_deadline  = $request->task_deadline;
        $task->people_names   = $request->people_names;

        $task->save();

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $task = Task::findOrFail($id);
      $task->delete();
      return back();
    }
}

resources/views/task/advancement.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
      <div class="row justify-content-center">
          <div class="col-md-3">
            @include('includes.sidebar')
          </div>
          <div class="col-md-9">
            <div class="card">
              <div class="card-body">
                  <h4 class="text-info text-center"> Task Advancement </h4>
                  <div class="card">
                      <div class="card-body">
                          <div class="row">
                              <div class="col-md-12">
                                  <table class="table table-bordered table-hover table-sm text-center">
                                      <thead>
                                        <th> Project Name </th>
                                          <th> Task </th>
                                          <th> Name </th>
                                          <th> Deadline </th>
                                          <th> Status </th>
                                      </thead>
                                      <tbody>
                                          @foreach ($tasks as $task)
                                              <tr>
                                                  <td> {{ $task->project->project_name }}</td>
                                                  <td> {{ $task->task_name }} </td>
                                                  <td> {{ $task->people_names }} </td>
                                                  <td> {{ $task->task_deadline}} </td>
                                                  <td>
                                                      @if ($task->task_progress == 1)
                                                        Ongoing
                                                      @else
                                                        Done
                                                      @endif
                                                  </td>
                                              </tr>
                                          @endforeach
                                      </tbody>
                                  </table>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
            </div>
          </div>
      </div>
  </div>
@endsection

resources/views/task/create.blade.php
<form id="task" action="{{ route('task.store') }}" method="post">
    @csrf
    <input type="hidden" name="project_id" value="{{ $project_id }}" />
    <div class="form-group">
        <label for="taskName"> Task Name: </label>
        <input type="text" name="task_name" id="taskName" class="form-control" required>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-lg-6">
                <label for="taskPriority"> Task Priority: </label>
                <select name="task_priority" class="form-control" id="taskPriority" required>
                    <option value="High"> High </option>
                    <option value="Low"> Low </option>
                </select>
            </div>
            <div class="col-lg-6">
                <label for="taskProgress"> Task Progress: </label>
                <select name="task_progress" class="form-control" id="taskProgress" required>
                    <option value="1"> Ongoing </option>
                    <option value="2"> Done </option>
                </select>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="deadline"> Deadline: </label>
        <input type="date" name="task_deadline" id="deadline" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="selectPeople"> Assign People: </label>
        <select class="form-control" name="people_names" id="selectPeople">
            @foreach ($peoples as $people)
            <option value="{{ $people->name}}"> {{ $people->name}} </option>
            @endforeach
        </select>
    </div>
</form>

resources/views/task/edit.blade.php
<form id="edittask" action="{{ route('task.update', $task->id) }}" method="post">
    @csrf @method('put')
    <input type="hidden" name="project_id" value="{{ $task->project_id }}" />
    <div class="form-group">
        <label for="taskName"> Task Name: </label>
        <input type="text" name="task_name" id="taskName" value="{{ $task->task_name}}" class="form-control">
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-lg-6">
                <label for="editTaskPriority"> Task Priority: </label>
                <select name="task_priority" class="form-control" id="editTaskPriority">
                  <option value="High" @if ($task->task_priority == "High")  selected @endif> High </option>
                  <option value="Low"  @if ($task->task_priority == "Low")  selected @endif> Low </option>
                </select>
            </div>
            <div class="col-lg-6">
                <label for="editTaskProgress"> Task Progress: </label>
                <select name="task_progress" class="form-control" id="editTaskProgress">
                  <option value="1" @if ($task->task_progress == "1")  selected @endif> Ongoing </option>
                  <option value="2"  @if ($task->task_progress == "2")  selected @endif> Done </option>
                </select>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="editdeadline"> Deadline: </label>
        <input type="date" name="task_deadline" id="editdeadline" value="{{ $task->task_deadline }}" class="form-control">
    </div>
    <div class="form-group">
        <label for="editSelectPeople"> Assign People: {{ $task->people_names }} </label>
        <select class="form-control" name="people_names" id="editSelectPeople">
            @foreach ($peoples as $people)
            <option value="{{ $people->name}}"> {{ $people->name}} </option>
            @endforeach
        </select>
    </div>
</form>