routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('project', 'ProjectController');

Route::resource('requirement', 'RequirementController')->except([
    'index', 'create'
]);
Route::resource('task', 'TaskController');

Route::resource('people', 'PeopleController');

Route::resource('meeting', 'MeetingController');

app/People.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class People extends Model
{
  protected $fillable = [
      'name', 'profession', 'email'
  ];
  public function task()
  {
      return $this->belongsTo('App\Task');
  }
}

app/Http/Controllers/PeopleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\People;
use Session;

class PeopleController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $peoples = People::all();
        return view('people.index',[ 'peoples' => $peoples]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
          'name' => 'required',
          'profession' => 'required',
          'email' => 'required|unique:people',
      ]);

        $people = new People();
        //$project = Project::findOrFail($id);

        $people->name = $request->name;
        $people->profession        = $request->profession;
        $people->email    = $request->email;

        $people->save();
        Session::flash( 'success', 'People has been successfully added.' );
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $people = People::findOrFail($id);
      return view('people.edit',['people' => $people]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
          'name' => 'required',
          'profession' => 'required',
          'email' => 'required',
      ]);

        $people = People::findOrFail($id);
        //$project = Project::findOrFail($id);

        $people->name = $request->name;
        $people->profession        = $request->profession;
        $people->email    = $request->email;

        $people->save();

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $people = People::findOrFail($id);
      $people->delete();
      return back();
    }
}

resources/views/people/create.blade.php
<form id="people" action="{{ route('people.store') }}" method="post">
    @csrf
    <div class="form-group">
        <label for="name"> Person Name: </label>
        <input type="text" name="name" id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}">
        @if ($errors->has('name'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
    </div>
    <div class="for-group">
        <label for="profession"> Person Profession: </label>
        <input type="text" name="profession" id="profession" class="form-control{{ $errors->has('profession') ? ' is-invalid' : '' }}">
        @if ($errors->has('profession'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('profession') }}</strong>
            </span>
        @endif
    </div>
    <div class="for-group">
        <label for="email"> Person E-mail: </label>
        <input type="email" name="email" id="email" value="{{ old('email') }}" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}">
        @if ($errors->has('email'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('email') }}</strong>
            </span>
        @endif
    </div>
</form>

resources/views/people/edit.blade.php
<form id="editpeople" action="{{ route('people.update',$people->id) }}" method="post">
    @csrf @method('put')
    <div class="form-group">
        <label for="name"> Person Name: </label>
        <input type="text" name="name" id="name" class="form-control" value="{{ $people->name }}" required>
    </div>
    <div class="for-group">
        <label for="profession"> Person Profession: </label>
        <input type="text" name="profession" id="profession" class="form-control" value="{{ $people->profession }}" required>
    </div>
    <div class="for-group">
        <label for="email"> Person E-mail: </label>
        <input type="email" name="email" id="email" class="form-control" value="{{ $people->email }}" required>
    </div>
</form>

resources/views/people/index.blade.php
@extends('layouts.app')

@section('title', 'People')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-3">
          @include('includes.sidebar')
        </div>
        <div class="col-md-9">
          @if(Session::has('success'))
            <div class="alert alert-success text-center" role="alert">
              <span> {{ Session::get('success') }} </span>
            </div>
          @endif
          <div class="card">
              <div class="card-header">
                <div class="row">
                  <div class="col-lg-6">
                      <h5> List of People </h5>
                  </div>
                  <div class="col-lg-6">
                    <div class="text-right">
                      <button type="button" class="btn btn-outline-success btn-sm" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#addPeopleModal">
                          <i class="fas fa-user-plus"></i> Add People
                      </button>
                    </div>
                    <!-- add Requirement modal code start -->
                    <div class="modal fade" id="addPeopleModal" tabindex="-1" role="dialog">
                      @if(count($errors) > 0)
                          <script type="text/javascript">
                            $('#addPeopleModal').modal('show');
                          </script>
                      @endif
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title"> Add People </h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true"> &times; </span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                  @include('people.create')
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-outline-danger btn-sm" data-dismiss="modal"> <i class="fas fa-times"></i> Close </button>
                                    <button form="people" type="submit" class="btn btn-outline-success btn-sm"> <i class="fas fa-plus"></i> Save </button>
                                </div>
                            </div>
                        </div>
                    </div> <!-- add Requirement modal code end -->
                  </div>
                </div>
              </div>
              <div class="card-body">
                <table class="table table-bordered table-hover table-sm">
                    <thead>
                        <th class="text-center"> Name </th>
                        <th class="text-center"> Profession </th>
                        <th class="text-center"> E-mail </th>
                        <th class="text-center"> Edit </th>
                        <th class="text-center"> Delete </th>
                    </thead>
                    <tbody>
                        @foreach ($peoples as $people)
                        <tr>
                            <td class="text-center"> {{ $people->name }} </td>
                            <td class="text-center"> {{ $people->profession }} </td>
                            <td class="text-center"> {{ $people->email }} </td>
                            <td>
                                <div class="text-center">
                                  <a href="{{route('people.edit', $people->id)}}" class="btn btn-outline-info btn-sm" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#editPeopleModal{{$people->id}}">
                                      <i class="fas fa-edit"></i>
                                  </a>
                                </div>
                                <!-- This below code edit madal Requirement -->
                                <div class="modal fade" id="editPeopleModal{{$people->id}}" tabindex="-1" role="dialog">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title"> Edit People </h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                  <span aria-hidden="true"> &times; </span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                              @include('people.edit')
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-outline-danger btn-sm" data-dismiss="modal"> <i class="fas fa-times"></i> Close </button>
                                                <button form="editpeople" type="submit" class="btn btn-outline-success btn-sm"> <i class="far fa-edit"></i> Save </button>
                                            </div>
                                        </div>
                                    </div>
                                </div> <!-- End of the edit Requirement modal code -->
                            </td>
                            <td class="text-center">
                              <form action="{{ route('people.destroy',$people->id)}}" method="post">
                                @csrf @method('delete')
                                <button type="submit" class="btn btn-outline-danger btn-sm"> <i class="far fa-trash-alt"></i> </button>
                              </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
              </div>
            </div>
        </div>
    </div>
</div>
@endsection